export const alert = {
  defaultPadding: '8px 12px',
  withDescriptionIconSize: 24,
  withDescriptionPadding: '20px 24px',
  colorError: '#ff4d4f',
  colorErrorBg: '#fff2f0',
  colorErrorBorder: '#ffccc7',
  colorIcon: 'rgba(0, 0, 0, 0.45)',
  colorIconHover: 'rgba(0, 0, 0, 0.88)',
  colorInfo: '#1677ff',
  colorInfoBg: '#e6f4ff',
  colorInfoBorder: '#91caff',
  colorSuccess: '#52c41a',
  colorSuccessBg: '#f6ffed',
  colorSuccessBorder: '#b7eb8f',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextHeading: 'rgba(0, 0, 0, 0.88)',
  colorWarning: '#faad14',
  colorWarningBg: '#fffbe6',
  colorWarningBorder: '#ffe58f',
  borderRadiusLG: 8,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeHeading3: 24,
  fontSizeIcon: 12,
  fontSizeLG: 16,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  marginSM: 12,
  marginXS: 8,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
  paddingContentHorizontalLG: 24,
  paddingContentVerticalSM: 8,
  paddingMD: 20,
};
