export const avatar = {
  containerSize: 32,
  containerSizeLG: 40,
  containerSizeSM: 24,
  groupBorderColor: '#ffffff',
  groupOverlapping: -8,
  groupSpace: 4,
  textFontSize: 18,
  textFontSizeLG: 24,
  textFontSizeSM: 14,
  colorBorderBg: '#ffffff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextLightSolid: '#fff',
  colorTextPlaceholder: 'rgba(0, 0, 0, 0.25)',
  borderRadius: 6,
  borderRadiusLG: 8,
  borderRadiusSM: 4,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeHeading3: 24,
  fontSizeLG: 16,
  fontSizeXL: 20,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  marginXS: 8,
  marginXXS: 4,
};
