export const cascader = {
  // component only
  controlItemWidth: 111,
  controlWidth: 184,
  dropdownHeight: 180,
  menuPadding: 4,
  optionPadding: '5px 12px',
  optionSelectedBg: '#e6f4ff',
  optionSelectedFontWeight: 600,
  // override global
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBorder: '#d9d9d9',
  colorHighlight: '#ff4d4f',
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorPrimaryHover: '#4096ff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDescription: 'rgba(0, 0, 0, 0.45)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorWhite: '#fff',
  borderRadiusSM: 4,
  controlHeight: 32,
  controlInteractiveSize: 16,
  controlItemBgActive: '#e6f4ff',
  controlItemBgHover: 'rgba(0, 0, 0, 0.04)',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeIcon: 12,
  fontSizeLG: 16,
  fontWeightStrong: 600,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthBold: 2,
  lineWidthFocus: 4,
  marginXS: 8,
  motionDurationFast: '0.1s',
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseInBack: 'cubic-bezier(0.71, -0.46, 0.88, 0.6)',
  motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
  paddingSM: 12,
  paddingXS: 8,
  paddingXXS: 4,
};
