export const layout = {
  bodyBg: '#f5f5f5',
  footerBg: '#f5f5f5',
  footerPadding: '24px 50px',
  headerBg: '#001529',
  headerColor: 'rgba(0, 0, 0, 0.88)',
  headerHeight: 64,
  headerPadding: '0 50px',
  lightSiderBg: '#ffffff',
  lightTriggerBg: '#ffffff',
  lightTriggerColor: 'rgba(0, 0, 0, 0.88)',
  siderBg: '#001529',
  triggerBg: '#002140',
  triggerColor: '#fff',
  triggerHeight: 48,
  zeroTriggerHeight: 40,
  zeroTriggerWidth: 40,
  colorBgContainer: '#ffffff',
  colorBgLayout: '#f5f5f5',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextLightSolid: '#fff',
  borderRadius: 6,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  fontSize: 14,
  fontSizeXL: 20,
  marginXXS: 4,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
};
