export const switchTheme = {
  handleBg: '#fff',
  handleShadow: '0 2px 4px 0 rgba(0, 35, 11, 0.2)',
  handleSize: 18,
  handleSizeSM: 12,
  innerMaxMargin: 24,
  innerMaxMarginSM: 18,
  innerMinMargin: 9,
  innerMinMarginSM: 6,
  trackHeight: 22,
  trackHeightSM: 16,
  trackMinWidth: 44,
  trackMinWidthSM: 28,
  trackPadding: 2,
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorPrimaryHover: '#4096ff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextLightSolid: '#fff',
  colorTextQuaternary: 'rgba(0, 0, 0, 0.25)',
  colorTextTertiary: 'rgba(0, 0, 0, 0.45)',
  colorWhite: '#fff',
  controlHeight: 32,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeIcon: 12,
  fontSizeSM: 12,
  lineHeight: 1.5714285714285714,
  lineWidthFocus: 4,
  marginXXS: 4,
  motion: true,
  motionDurationMid: '0.2s',
  opacityLoading: 0.65,
};
