export const table = {
  bodySortBg: '#fafafa',
  borderColor: '#f0f0f0',
  cellFontSize: 14,
  cellFontSizeMD: 14,
  cellFontSizeSM: 14,
  cellPaddingBlock: 16,
  cellPaddingBlockMD: 12,
  cellPaddingBlockSM: 8,
  cellPaddingInline: 16,
  cellPaddingInlineMD: 8,
  cellPaddingInlineSM: 8,
  expandIconBg: '#ffffff',
  filterDropdownBg: '#ffffff',
  filterDropdownMenuBg: '#ffffff',
  fixedHeaderSortActiveBg: '#f0f0f0',
  footerBg: '#fafafa',
  footerColor: 'rgba(0, 0, 0, 0.88)',
  headerBg: '#fafafa',
  headerBorderRadius: 8,
  headerColor: 'rgba(0, 0, 0, 0.88)',
  headerFilterHoverBg: 'rgba(0, 0, 0, 0.06)',
  headerSortActiveBg: '#f0f0f0',
  headerSortHoverBg: '#f0f0f0',
  headerSplitColor: '#f0f0f0',
  rowExpandedBg: 'rgba(0, 0, 0, 0.02)',
  rowHoverBg: '#fafafa',
  rowSelectedBg: '#e6f4ff',
  rowSelectedHoverBg: '#bae0ff',
  selectionColumnWidth: 32,
  stickyScrollBarBg: 'rgba(0, 0, 0, 0.25)',
  stickyScrollBarBorderRadius: 100,
  colorBgContainer: '#ffffff',
  colorBorderSecondary: '#f0f0f0',
  colorFillAlter: 'rgba(0, 0, 0, 0.02)',
  colorFillContent: 'rgba(0, 0, 0, 0.06)',
  colorFillSecondary: 'rgba(0, 0, 0, 0.06)',
  colorIcon: 'rgba(0, 0, 0, 0.45)',
  colorIconHover: 'rgba(0, 0, 0, 0.88)',
  colorLink: '#1677ff',
  colorLinkActive: '#0958d9',
  colorLinkHover: '#69b1ff',
  colorPrimary: '#1677ff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDescription: 'rgba(0, 0, 0, 0.45)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorTextHeading: 'rgba(0, 0, 0, 0.88)',
  colorTextPlaceholder: 'rgba(0, 0, 0, 0.25)',
  borderRadius: 6,
  borderRadiusLG: 8,
  boxShadowSecondary:
    '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
  controlHeight: 32,
  controlInteractiveSize: 16,
  controlItemBgActive: '#e6f4ff',
  controlItemBgActiveHover: '#bae0ff',
  controlItemBgHover: 'rgba(0, 0, 0, 0.04)',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeIcon: 12,
  fontSizeSM: 12,
  fontWeightStrong: 600,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  margin: 16,
  marginXXS: 4,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  opacityLoading: 0.65,
  padding: 16,
  paddingSM: 12,
  paddingXS: 8,
  paddingXXS: 4,
};
