export const transfer = {
  headerHeight: 40,
  itemHeight: 32,
  itemPaddingBlock: 5,
  listHeight: 200,
  listWidth: 180,
  listWidthLG: 250,
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBorder: '#d9d9d9',
  colorError: '#ff4d4f',
  colorLinkHover: '#69b1ff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorWarning: '#faad14',
  borderRadiusLG: 8,
  controlHeight: 32,
  controlHeightLG: 40,
  controlItemBgActive: '#e6f4ff',
  controlItemBgActiveHover: '#bae0ff',
  controlItemBgHover: 'rgba(0, 0, 0, 0.04)',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeIcon: 12,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  margin: 16,
  marginXS: 8,
  marginXXS: 4,
  motionDurationSlow: '0.3s',
  paddingSM: 12,
  paddingXS: 8,
};
