export const badge = {
  dotSize: 6,
  indicatorHeight: 20,
  indicatorHeightSM: 14,
  indicatorZIndex: 'auto',
  statusSize: 6,
  textFontSize: 12,
  textFontSizeSM: 12,
  textFontWeight: 'normal',
  colorBgContainer: '#ffffff',
  colorBorderBg: '#ffffff',
  colorError: '#ff4d4f',
  colorErrorHover: '#ff7875',
  colorPrimary: '#1677ff',
  colorSuccess: '#52c41a',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextPlaceholder: 'rgba(0, 0, 0, 0.25)',
  colorWarning: '#faad14',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeSM: 12,
  lineHeight: 1.5714285714285714,
  lineWidth: 1,
  marginXS: 8,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
  paddingXS: 8,
};
