export const collapse = {
  contentBg: '#ffffff',
  contentPadding: '16px 16px',
  headerBg: 'rgba(0, 0, 0, 0.02)',
  headerPadding: '12px 16px',
  colorBgContainer: '#ffffff',
  colorBorder: '#d9d9d9',
  colorFillAlter: 'rgba(0, 0, 0, 0.02)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorTextHeading: 'rgba(0, 0, 0, 0.88)',
  borderRadiusLG: 8,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeIcon: 12,
  fontSizeLG: 16,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  marginSM: 12,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  padding: 16,
  paddingLG: 24,
  paddingSM: 12,
  paddingXS: 8,
  paddingXXS: 4,
};
