export const list = {
  avatarMarginRight: 16,
  contentWidth: 220,
  descriptionFontSize: 14,
  emptyTextPadding: 16,
  footerBg: 'transparent',
  headerBg: 'transparent',
  itemPadding: '12px 0',
  itemPaddingLG: '16px 24px',
  itemPaddingSM: '8px 16px',
  metaMarginBottom: 16,
  titleMarginBottom: 12,
  colorBorder: '#d9d9d9',
  colorPrimary: '#1677ff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDescription: 'rgba(0, 0, 0, 0.45)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  borderRadiusLG: 8,
  controlHeight: 32,
  controlHeightLG: 40,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeLG: 16,
  fontSizeSM: 12,
  lineHeight: 1.5714285714285714,
  lineHeightLG: 1.5,
  lineType: 'solid',
  lineWidth: 1,
  margin: 16,
  marginLG: 24,
  marginSM: 12,
  marginXXL: 48,
  marginXXS: 4,
  motionDurationSlow: '0.3s',
  padding: 16,
  paddingContentHorizontal: 16,
  paddingContentHorizontalLG: 24,
  paddingContentVertical: 12,
  paddingContentVerticalLG: 16,
  paddingContentVerticalSM: 8,
  paddingLG: 24,
  paddingSM: 12,
  paddingXS: 8,
  screenMD: 768,
  screenSM: 576,
};
