export const pagination = {
  itemActiveBg: '#ffffff',
  itemActiveBgDisabled: 'rgba(0, 0, 0, 0.15)',
  itemActiveColorDisabled: 'rgba(0, 0, 0, 0.25)',
  itemBg: '#ffffff',
  itemInputBg: '#ffffff',
  itemLinkBg: '#ffffff',
  itemSize: 32,
  itemSizeSM: 24,
  miniOptionsSizeChangerTop: 0,
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBgTextActive: 'rgba(0, 0, 0, 0.15)',
  colorBgTextHover: 'rgba(0, 0, 0, 0.06)',
  colorBorder: '#d9d9d9',
  colorFillAlter: 'rgba(0, 0, 0, 0.02)',
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorPrimaryHover: '#4096ff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorTextPlaceholder: 'rgba(0, 0, 0, 0.25)',
  borderRadius: 6,
  borderRadiusLG: 8,
  borderRadiusSM: 4,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  controlItemBgActiveDisabled: 'rgba(0, 0, 0, 0.15)',
  controlOutline: 'rgba(5, 145, 255, 0.1)',
  controlOutlineWidth: 2,
  controlPaddingHorizontal: 12,
  controlPaddingHorizontalSM: 8,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeLG: 16,
  fontSizeSM: 12,
  fontWeightStrong: 600,
  lineHeight: 1.5714285714285714,
  lineHeightLG: 1.5,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthFocus: 4,
  margin: 16,
  marginSM: 12,
  marginXS: 8,
  marginXXS: 4,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  paddingSM: 12,
  paddingXXS: 4,
  screenLG: 992,
  screenSM: 576,
  wireframe: false,
};
