export const radio = {
  buttonBg: '#ffffff',
  buttonCheckedBg: '#ffffff',
  buttonCheckedBgDisabled: 'rgba(0, 0, 0, 0.15)',
  buttonCheckedColorDisabled: 'rgba(0, 0, 0, 0.25)',
  buttonColor: 'rgba(0, 0, 0, 0.88)',
  buttonPaddingInline: 15,
  buttonSolidCheckedActiveBg: '#0958d9',
  buttonSolidCheckedBg: '#1677ff',
  buttonSolidCheckedColor: '#fff',
  buttonSolidCheckedHoverBg: '#4096ff',
  dotColorDisabled: 'rgba(0, 0, 0, 0.25)',
  dotSize: 8,
  radioSize: 16,
  wrapperMarginInlineEnd: 8,
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBorder: '#d9d9d9',
  colorPrimary: '#1677ff',
  colorPrimaryActive: '#0958d9',
  colorPrimaryBorder: '#91caff',
  colorPrimaryHover: '#4096ff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorTextLightSolid: '#fff',
  colorWhite: '#fff',
  borderRadius: 6,
  borderRadiusLG: 8,
  borderRadiusSM: 4,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  controlItemBgActiveDisabled: 'rgba(0, 0, 0, 0.15)',
  controlOutline: 'rgba(5, 145, 255, 0.1)',
  controlOutlineWidth: 2,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeLG: 16,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthFocus: 4,
  marginXS: 8,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
  padding: 16,
  paddingXS: 8,
  wireframe: false,
};
