export const slider = {
  controlSize: 10,
  dotActiveBorderColor: '#91caff',
  dotBorderColor: '#f0f0f0',
  dotSize: 8,
  handleActiveColor: '#1677ff',
  handleColor: '#91caff',
  handleLineWidth: 2,
  handleLineWidthHover: 4,
  handleSize: 10,
  handleSizeHover: 12,
  railBg: 'rgba(0, 0, 0, 0.04)',
  railHoverBg: 'rgba(0, 0, 0, 0.06)',
  railSize: 4,
  trackBg: '#91caff',
  trackBgDisabled: 'rgba(0, 0, 0, 0.04)',
  trackHoverBg: '#69b1ff',
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBgElevated: '#ffffff',
  colorBorderSecondary: '#f0f0f0',
  colorFillContentHover: 'rgba(0, 0, 0, 0.15)',
  colorFillSecondary: 'rgba(0, 0, 0, 0.06)',
  colorFillTertiary: 'rgba(0, 0, 0, 0.04)',
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorPrimaryBorderHover: '#69b1ff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDescription: 'rgba(0, 0, 0, 0.45)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  borderRadiusXS: 2,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  lineHeight: 1.5714285714285714,
  lineWidth: 1,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
};
