export const steps = {
  customIconFontSize: 24,
  customIconSize: 32,
  customIconTop: 0,
  descriptionMaxWidth: 140,
  dotCurrentSize: 10,
  dotSize: 8,
  iconFontSize: 14,
  iconSize: 32,
  iconSizeSM: 24,
  iconTop: -0.5,
  navArrowColor: 'rgba(0, 0, 0, 0.25)',
  navContentMaxWidth: 'auto',
  titleLineHeight: 32,
  colorBgContainer: '#ffffff',
  colorBorderBg: '#ffffff',
  colorBorderSecondary: '#f0f0f0',
  colorError: '#ff4d4f',
  colorFillContent: 'rgba(0, 0, 0, 0.06)',
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDescription: 'rgba(0, 0, 0, 0.45)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorTextLabel: 'rgba(0, 0, 0, 0.65)',
  colorTextLightSolid: '#fff',
  colorTextQuaternary: 'rgba(0, 0, 0, 0.25)',
  borderRadiusSM: 4,
  controlHeight: 32,
  controlHeightLG: 40,
  controlHeightSM: 24,
  controlItemBgActive: '#e6f4ff',
  controlItemBgHover: 'rgba(0, 0, 0, 0.04)',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeHeading3: 24,
  fontSizeIcon: 12,
  fontSizeLG: 16,
  fontSizeSM: 12,
  fontWeightStrong: 600,
  lineHeight: 1.5714285714285714,
  lineHeightSM: 1.6666666666666667,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthBold: 2,
  lineWidthFocus: 4,
  margin: 16,
  marginLG: 24,
  marginSM: 12,
  marginXS: 8,
  marginXXS: 4,
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  padding: 16,
  paddingLG: 24,
  paddingSM: 12,
  paddingXS: 8,
  paddingXXS: 4,
  wireframe: false,
};
