export const timeline = {
  dotBg: '#ffffff',
  dotBorderWidth: 2,
  itemPaddingBottom: 20,
  tailColor: 'rgba(5, 5, 5, 0.06)',
  tailWidth: 2,
  colorBgContainer: '#ffffff',
  colorError: '#ff4d4f',
  colorPrimary: '#1677ff',
  colorSplit: 'rgba(5, 5, 5, 0.06)',
  colorSuccess: '#52c41a',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  controlHeightLG: 40,
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeSM: 12,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthBold: 2,
  margin: 16,
  marginSM: 12,
  marginXS: 8,
  marginXXS: 4,
  padding: 16,
  paddingXXS: 4,
  wireframe: false,
};
