export const treeSelect = {
  nodeHoverBg: 'rgba(0, 0, 0, 0.04)',
  nodeSelectedBg: '#e6f4ff',
  titleHeight: 24,
  colorBgContainer: '#ffffff',
  colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
  colorBgElevated: '#ffffff',
  colorBorder: '#d9d9d9',
  colorPrimary: '#1677ff',
  colorPrimaryBorder: '#91caff',
  colorPrimaryHover: '#4096ff',
  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextDisabled: 'rgba(0, 0, 0, 0.25)',
  colorWhite: '#fff',
  borderRadius: 6,
  borderRadiusSM: 4,
  controlHeightSM: 24,
  controlInteractiveSize: 16,
  controlItemBgActive: '#e6f4ff',
  controlItemBgHover: 'rgba(0, 0, 0, 0.04)',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  fontSize: 14,
  fontSizeLG: 16,
  lineHeight: 1.5714285714285714,
  lineType: 'solid',
  lineWidth: 1,
  lineWidthBold: 2,
  lineWidthFocus: 4,
  marginXS: 8,
  marginXXS: 4,
  motionDurationFast: '0.1s',
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
  motionEaseInBack: 'cubic-bezier(0.71, -0.46, 0.88, 0.6)',
  motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
  paddingXS: 8,
};
